#!/usr/bin/python
from deslicer_server import main
import sys
import os
import traceback

if __name__=='__main__':
  if '-d' in sys.argv:
#    from deslicer_server import deamon
    os.chdir('/var/lib/deslicer/')
#  else:
  try:
    main.initial_program_setup()
    main.reload_program_config()
    main.do_main_program()
  except Exception as e:
    print (traceback.format_exc())
    main.program_cleanup()
    raise e

